//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmKveldApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmer
    {
        public int Film_Id { get; set; }
        public string Tittel { get; set; }
        public string Bilde { get; set; }
        public Nullable<int> Utgivelsesaar { get; set; }
        public string Beskrivelse { get; set; }
        public Nullable<int> Kategori_Id { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
